version: '3'
services:
  # front:
  #   build:
  #     context: ./front
  #   container_name: front
  #   ports:
  #     - 8080:80
  #   networks:
  #     – mynet
  back:
    build:
      context: ./back
    container_name: back
    environment:
      HOST: 0.0.0.0
      PORT: 81
      DB_HOST: db
      DB_USER: db_user
      DB_PASSWORD: 1234
      COMPANY_SECRET: company_secret
      FREEL_SECRET: freel_secret
      COMPANY_AUDIENCE: tikhonov
      FREEL_AUDIENCE: pesotskiy
  #      REALM: soloteam
  #      ALLOW_HOST: *
      REFRESH: 10000000
      ACCESS: 30000
    ports:
      - "81:81"
    depends_on:
      - db
    networks:
      - mynet
#    volumes:
#      - "./logs:testFile.log"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: main
      MYSQL_USER: db_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - "./mysql-data:/var/lib/mysql"
    networks: 
      - mynet  
networks:
  mynet:
    driver: bridge