version: '3'
services:
  # front:
  #   build:
  #     context: ./back
  #   container_name: front
  #   ports:
  #     - 8080:80
  #   networks:
  #     – mynet
  back:
    build:
      context: ./front
    container_name: back
    environment:
      – DB_HOST=db
    ports:
      - 81:8080
    networks:
      – mynet
  db:
    image: mysql:5.7
    environment:
      – MYSQL_ROOT_PASSWORD=secret
      – MYSQL_DATABASE=mydatabase
    ports:
      – "3306:3306"
    volumes:
      – mysql-data:/var/lib/mysql
    networks:
      – mynet
volumes:
  mysql-data:
networks:
  mynet:
    driver: bridge