version: '3'
services:
  front:
     build:
       context: ./front
     container_name: front
     environment:
       back: api
       access: access
       refresh: refresh
       type_name: type_name
       password_length: 6
     ports:
       - "8080:80"
     networks:
       - mynet
  back:
    build:
      context: ./back
    container_name: back
    environment:
      HOST: 0.0.0.0
      PORT: 81
      ROOT_PATH: /api
      DB_HOST: db
      DB_USER:
      DB_PASSWORD:
      DB_PORT: 3306
      COMPANY_SECRET:
      FREEL_SECRET:
      COMPANY_AUDIENCE:
      FREEL_AUDIENCE:
      DB_TABLE:
      REFRESH: 604800000
      ACCESS: 60000
      RECOVERY: 604800000
      PAYMENT_EXPIRED_DAYS: 61
      REGISTRATION_PATH: https://soloteam.io/app/signup?link=
      RECOVERY_PATH: https://soloteam.io/app/reset-password?code=
      #      SMTP_SERVICE_LOGIN
      #      SMTP_SERVICE_PASSWORD:
      SMTP_HELLO_LOGIN: hello@soloteam.io
      SMTP_HELLO_PASSWORD:
      #      SMTP_INFO_LOGIN
      #      SMTP_INFO_PASSWORD:
      SMTP_NOREPLAY_LOGIN: noreplay@soloteam.io
      SMTP_NOREPLAY_PASSWORD:
    ports:
      - "81:81"
    depends_on:
      - db
    networks:
      - mynet
#    volumes:
#      - "./logs/log.log:testFile/log"
  db:
    build: 
      context: .
      dockerfile: Dbdockerfile
    container_name: db
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_INITDB_CHARSET: utf8mb4
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
    networks:
      - mynet
volumes:
  mysql_data:
networks:
  mynet:
    driver: bridge