ktor:
  application:
    modules:
      - com.heisy.ApplicationKt.module
  deployment:
    port: "$PORT:81"
    host: "$HOST:0.0.0.0"
    rootPath: "$ROOT_PATH:/api"
    db: "$DB_HOST:127.0.0.1"
    db_user: "$DB_USER:db_user"
    db_password: "$DB_PASSWORD:1234"
    db_port: "$DB_PORT:3306"
    db_table: "$DB_TABLE:main"
    key: "$KEY:1"
jwt:
  company_secret: "$COMPANY_SECRET"
  freel_secret: "$FREEL_SECRET"
  company_audience: "$COMPANY_AUDIENCE"
  freel_audience: "$FREEL_AUDIENCE"
  realm: "$REALM:soloteam"
  allow_host: "$ALLOW_HOST:*"
  refresh_lifetime: "$REFRESH:100000000"
  access_lifetime: "$ACCESS:60000"
smtp:
  no_replay:
    login: "$SMTP_NOREPLAY_LOGIN"
#    password: "$SMTP_NOREPLAY_PASSWORD"
#  info:
#    login: "$SMTP_INFO_LOGIN"
#    password: "$SMTP_INFO_PASSWORD"
#  hello:
#    login: "$SMTP_HELLO_LOGIN"
#    password: "$SMTP_HELLO_PASSWORD"
#  service:
#    login: "$SMTP_SERVICE_LOGIN"
#    password: "$SMTP_SERVICE_PASSWORD"
path:
  registration: "$REGISTRATION_PATH"
  recovery: "$RECOVERY_PATH"
recovery:
  password: "$RECOVERY"
payment:
  expired_days: "$PAYMENT_EXPIRED_DAYS:61"