ktor:
  application:
    modules:
      - com.heisy.ApplicationKt.module
  deployment:
#    domain: "$DOMAIN"
    port: "$PORT:81"
    host: "$HOST:0.0.0.0"
    db: "$DB_HOST:127.0.0.1"
    db_user: "$DB_USER:db_user"
    db_password: "$DB_PASSWORD:1234"
    db_port: "$DB_PORT:3306"
    db_table: "$DB_TABLE:main"
jwt:
  company_secret: "$COMPANY_SECRET:company_secret"
  freel_secret: "$FREEL_SECRET:freel_secret"
  company_audience: "$COMPANY_AUDIENCE:company_audience"
  freel_audience: "$FREEL_AUDIENCE:freel_audience"
  realm: "$REALM:soloteam"
  allow_host: "$ALLOW_HOST:*"
  refresh_lifetime: "$REFRESH:100000000"
  access_lifetime: "$ACCESS:30000"
#smtp:
#  no_replay:
#    login: "$SMTP_NOREPLAY_LOGIN"
#    password: "$SMTP_NOREPLAY_PASSWORD"
#  info:
#    login: "$SMTP_INFO_LOGIN"
#    password: "$SMTP_INFO_PASSWORD"
#  hello:
#    login: "$SMTP_HELLO_LOGIN"
#    password: "$SMTP_HELLO_PASSWORD"
#  service:
#    login: "$SMTP_SERVICE_LOGIN"
#    password: "$SMTP_SERVICE_PASSWORD"
path:
  registration: "$REGISTRATION_PATH:http://localhost:3100/signup?link="
  #  recovery: "$RECOVERY_PATH"
recovery:
  password: "$RECOVERY:604800000"
